application: csihackon2017
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /images
  static_dir: images
- url: /img
  static_dir: img
- url: /inc
  static_dir: inc
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /bower_components
  static_dir: bower_components
- url: /
  static_files: index.html
  upload: index.html
- url: /.*
  static_files: 404.html
  upload: 404.html
